---
title: "STAT 184 Homework Exercises" 
subtitle: "DataComputing Chapters 17"
author: "eric weah"
output: html_notebook
---

## Assigned Exercises

- DC Chapter 17 Exercises: 17.1,17.3,17.4,17.5,17.7


## Front Matter

```{r}
# clean up workspace environment
rm(list = ls())

# all packages used for the assignment
library(mosaic)
library(tidyverse)
library(DataComputing)
library(tidyverse)
library(tidyr)
library(lubridate)

```



## Chapter 1 Exercises

### Problem 17.1
a.)
```{r}
regex<- ".*([aeiou])$"
boy_names<-BabyNames%>%group_by(name)%>%filter(grepl(pattern = regex,name),sex=="M")%>%summarise(s=sum(count))%>%filter(rank(desc(s))<=10)
regex
```

b.) There seems to be no results for this 
```{r}
BabyNames%>%
  group_by(sex,name)%>%
  filter(grepl("\\s", name))%>%
  summarise(total=sum(count))%>%
  arrange(desc(total))%>%
  head(10)

```
c.)
```{r}
BabyNames%>%
  group_by(name)%>%
  filter(grepl("Joe$|joe$", name))%>%
  summarise(total=sum(count))%>%
  arrange(desc(total))%>%
  head(10)

```

